### ISSUE TITLE
左侧控制器如何实现push一个另外一个控制器呢

### ISSUE THREAD

**Issue by pasmall** [maybeisyi/DYLeftSlipManager#1]

**Comment by maybeisyi** [comment]
1、push另一个控制器，那么这次push肯定是在主界面做的，左侧控制器无论在业务上还是界面结构上，都不应该push出一个新的控制器。
2、根据你想要的效果，应该是在左侧控制器内触发某个事件，如点击某个按钮/cell，dismiss掉左侧控制器，同时触发push动作。此时涉及到主界面和左侧控制器的通信。由于两者之间没有耦合，那么通信方式可以可选NSNotification。当然还有一个方式是URL Scheme。在目前有很多的应用都是通过URL Scheme的方式实现业务跳转，该方式比较灵活、通用，同时耦合性较小。
3、当然还有一种方式，扩展DYLeftSlipManager，加上dismiss时同时触发的block，让主控制器实现向[DYLeftSlipManager sharedManager]进行业务注册。
希望对你有帮助~

**Comment by pasmall** [comment]
嗯嗯，谢谢哈，“dismiss掉左侧控制器，同时触发push动作” ，我左侧页面和主页面通信完成的，不过我觉得还是该试试URL Scheme 来实现业务跳转的路由，谢谢大神。
