### ISSUE TITLE
在iOS13上，第一个左滑会黑屏

### ISSUE THREAD

**Issue by IslandMask** [maybeisyi/DYLeftSlipManager#6]
在iOS13上，第一个左滑打开左边，再回去会黑屏，但是不闪退，也不报错，题主能更新下不，在线等，挺急的

**Comment by IslandMask** [comment]
我的是13.1.3，题主试下，百分百黑屏，你的demo也是，我没找出原因

**Comment by IslandMask** [comment]
找到原因了，坑爹的iOS13

**Comment by jackwuzz** [comment]
兄台，找到什么原因了吗

**Comment by jackwuzz** [comment]
解决办法：设置vc的modalPresentationStyle为UIModalPresentationFullScreen

举例如下：
LeftVC.modalPresentationStyle = UIModalPresentationFullScreen;
coverVC.modalPresentationStyle = UIModalPresentationFullScreen;
[[ERLeftSlipManager sharedManager] setLeftViewController:LeftVC   coverViewController:coverVC];

原因：iOS13 下，UIKit默认的modalPresentationStyle不是UIModalPresentationFullScreen，所以要提前设置一下

**Comment by maybeisyi** [comment]
兄弟牛批！一直没上邮箱没有看到，不好意思哈！
会尽快更新代码的！


| |
戴奕
|
|
daybyte@163.com
|
签名由网易邮箱大师定制


在2019年10月31日 21:06，jackWu<notifications@github.com> 写道：

解决办法：设置vc的modalPresentationStyle为UIModalPresentationFullScreen

举例如下：
LeftVC.modalPresentationStyle = UIModalPresentationFullScreen;
coverVC.modalPresentationStyle = UIModalPresentationFullScreen;
[[ERLeftSlipManager sharedManager] setLeftViewController:LeftVC coverViewController:coverVC];

原因：iOS13 下，UIKit默认的modalPresentationStyle不是UIModalPresentationFullScreen，所以要提前设置一下

**Comment by maybeisyi** [comment]
已修复
